[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "online_pykv"
version = "0.1.0"
description = "Python client for kv.osmosis.page"
requires-python = ">=3.11"
dependencies = ["qrcode", "tomli_w", "cryptography"]

[project.optional-dependencies]
dev = ["pytest"]
